#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

ROOT_DIR = Path(__file__).resolve().parents[1]
TS_SCHEMA_PATH = ROOT_DIR / "src" / "core" / "state-schema.ts"
PY_SCHEMA_PATH = ROOT_DIR / "scripts" / "_state_schema.py"
JSON_SCHEMA_PATH = ROOT_DIR / "state-schema.json"

EXPORT_NAMES = ("TASK_STATUSES", "TERMINAL", "TRANSITIONS", "RECOVERY_ACTIONS", "ACTIVE_PHASE_STATUSES")


def _extract_export(source: str, export_name: str) -> Any:
    pattern = re.compile(
        rf"export const {export_name}(?:\s*:[^=]+)?\s*=\s*(?P<value>.*?)\s*as const\s*;",
        re.DOTALL,
    )
    match = pattern.search(source)
    if not match:
        raise ValueError(f"Missing export: {export_name}")
    try:
        return json.loads(match.group("value"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON literal in export {export_name}: {exc}") from exc


def _ensure_unique(values: list[str], label: str) -> list[str]:
    deduped = list(dict.fromkeys(values))
    if len(deduped) != len(values):
        raise ValueError(f"Duplicate entries are not allowed in {label}")
    return deduped


def _normalize_schema(schema: dict[str, Any]) -> dict[str, Any]:
    task_statuses = _ensure_unique(list(schema["TASK_STATUSES"]), "TASK_STATUSES")
    terminal = _ensure_unique(list(schema["TERMINAL"]), "TERMINAL")
    recovery_actions = _ensure_unique(list(schema["RECOVERY_ACTIONS"]), "RECOVERY_ACTIONS")
    active_phase_statuses = _ensure_unique(list(schema["ACTIVE_PHASE_STATUSES"]), "ACTIVE_PHASE_STATUSES")

    status_set = set(task_statuses)
    if not set(terminal).issubset(status_set):
        raise ValueError("TERMINAL must be a subset of TASK_STATUSES")

    transitions_in: list[dict[str, Any]] = list(schema["TRANSITIONS"])
    transitions_out: list[dict[str, str]] = []
    for transition in transitions_in:
        from_status = str(transition["from"])
        to_status = str(transition["to"])
        condition = str(transition["condition"])
        guard = transition.get("guard")

        if from_status != "*" and from_status not in status_set:
            raise ValueError(f"Unknown transition from status: {from_status}")
        if to_status not in status_set:
            raise ValueError(f"Unknown transition to status: {to_status}")

        normalized: dict[str, str] = {
            "from": from_status,
            "to": to_status,
            "condition": condition,
        }
        if guard is not None:
            normalized["guard"] = str(guard)
        transitions_out.append(normalized)

    return {
        "task_statuses": task_statuses,
        "terminal": terminal,
        "transitions": transitions_out,
        "recovery_actions": recovery_actions,
        "active_phase_statuses": active_phase_statuses,
    }


def _render_python(schema: dict[str, Any]) -> str:
    task_statuses = tuple(schema["task_statuses"])
    terminal = tuple(schema["terminal"])
    transitions = schema["transitions"]
    recovery_actions = tuple(schema["recovery_actions"])
    active_phase_statuses = tuple(schema["active_phase_statuses"])

    transitions_block = json.dumps(transitions, indent=2, ensure_ascii=True)
    transitions_block = transitions_block.replace("true", "True").replace("false", "False").replace("null", "None")

    lines = [
        "# Generated by scripts/build_state_schema.py. DO NOT EDIT.",
        "from __future__ import annotations",
        "",
        f"TASK_STATUSES = {task_statuses!r}",
        f"TERMINAL = frozenset({terminal!r})",
        f"TRANSITIONS = {transitions_block}",
        f"RECOVERY_ACTIONS = {recovery_actions!r}",
        f"ACTIVE_PHASE_STATUSES = frozenset({active_phase_statuses!r})",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    source = TS_SCHEMA_PATH.read_text(encoding="utf-8")
    extracted = {name: _extract_export(source, name) for name in EXPORT_NAMES}
    normalized = _normalize_schema(extracted)

    python_text = _render_python(normalized)
    json_text = json.dumps(normalized, ensure_ascii=True, indent=2, sort_keys=True) + "\n"

    PY_SCHEMA_PATH.write_text(python_text, encoding="utf-8")
    JSON_SCHEMA_PATH.write_text(json_text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
