export interface SettingMeta {
  description: string;
  options?: string[];
}

export const SETTING_DESCRIPTIONS: Record<string, string | SettingMeta> = {
  'version': '현재 플러그인 버전',
  'plugin_name': '플러그인 이름',
  'branding.name': '브랜딩 이름',
  'branding.tagline': '브랜딩 태그라인',
  'workflow.max_feedback_rounds': '최대 피드백 반복 횟수 (Phase 4)',
  'workflow.auto_approve_spec': '스펙 자동 승인 여부',
  'workflow.auto_accept_result': 'Phase 3 리뷰 PASS 후 자동 수락',
  'workflow.default_agent': { description: '기본 실행 에이전트', options: ['codex-dev', 'agy-dev', 'claude-dev'] },
  'workflow.spec_prereview': '스펙 작성 후 구현 전 Pre-review Pass 실행 여부',
  'agile.steering_every': 'Steering 실행 간격 (스프린트 단위)',
  'agile.drift_threshold': 'Drift 임계값',
  'agile.drift_count_trigger': 'Drift 연속 발생 트리거 횟수',
  'agile.no_diff_count_trigger': '무변경 연속 트리거 횟수',
  'agile.convergence_threshold_abs': '수렴 절대 임계값 (D_t)',
  'agile.convergence_threshold_trend': '수렴 추세 임계값 (EMA3)',
  'agile.soft_limit_small': '소규모 라운드 soft limit',
  'agile.soft_limit_large': '대규모 라운드 soft limit',
  'agile.round_history_max_summary_lines': '라운드 히스토리 최대 요약 라인 수',
  'agile.evidence_gate': 'Sprint Review evidence gate 기본 설정',
  'agile.evidence_gate.enabled': 'Evidence gate 활성화 여부',
  'agile.evidence_gate.required_globs': '프로젝트 산출물 필수 glob 목록',
  'agile.dispatch': 'Sprint dispatch 실행 설정',
  'agile.dispatch.enabled': 'Sprint dispatch 활성화 여부',
  'agile.dispatch.default_mode': { description: 'Sprint 실행 기본 모드', options: ['inline', 'dispatch'] },
  'agile.dispatch.provider': { description: 'Sprint dispatch 기본 provider', options: ['codex', 'agy', 'claude'] },
  'agile.drift': 'Objective Surface Coverage 기반 drift 감지 설정',
  'agile.drift.enabled': 'Drift 체크 활성화 여부',
  'agile.drift.threshold': 'Drift PASS 판정 최소 커버리지 비율',
  'agile.drift.warn_streak_limit': 'WARN 연속 발생 시 escalate 되는 기준 횟수',
  'agile.recall': 'agile-plan recall 재호출 정책',
  'agile.recall.enabled': 'Recall 기능 활성화 여부',
  'agile.recall.cooldown_ratio': '프로젝트 크기 대비 recall cooldown 비율',
  'agile.recall.cooldown_floor': 'Recall cooldown 최소 스프린트 수',
  'agile.recall.cooldown_ceiling': 'Recall cooldown 최대 스프린트 수',
  'agile.recall.cap_ratio': '프로젝트 크기 대비 recall cap 비율',
  'agile.recall.cap_floor': 'Recall cap 최소 허용 횟수',
  'agile.recall.cap_ceiling': 'Recall cap 최대 허용 횟수',
  'agile.recall.level3_cooldown_multiplier': 'Level 3 recall cooldown 배수',
  'agile.recall.patch_budget_max': '단일 sprint recall 최대 patch 수',
  'agile.recall.patch_budget_ratio': '완료 DoD 대비 recall patch budget 비율',
  'agile.unlock': 'Done DoD unlock 재개방 정책',
  'agile.unlock.enabled': 'Unlock 경로 활성화 여부',
  'agile.unlock.reason_min_length': 'Unlock reason 최소 글자 수',
  'agile.unlock.reason_max_length': 'Unlock reason 최대 글자 수',
  'agile.unlock.forbidden_patterns': 'Unlock reason에서 금지할 패턴 목록',
  'agile.adversarial_review': 'D3 Gate 직전 적대적 검토 게이트 설정',
  'agile.adversarial_review.enabled': '적대적 검토 게이트 전체 활성화 여부',
  'agile.adversarial_review.perspectives.edge.enabled': '엣지케이스 관점 검토 활성화 여부',
  'agile.adversarial_review.perspectives.flow.enabled': '누락된 흐름 관점 검토 활성화 여부',
  'agile.adversarial_review.perspectives.integration.enabled': '통합 경계 관점 검토 활성화 여부',
  'agile.adversarial_review.perspectives.persona.enabled': '페르소나 gap 관점 검토 활성화 여부',
  'agile.adversarial_review.perspectives.nfr.enabled': '비기능 요구사항 gap 관점 검토 활성화 여부',
  'agile.adversarial_review.max_rounds': '적대적 검토 최대 반복 라운드 수',
  'agile.adversarial_review.auto_apply_severity_threshold': { description: 'AUTO_MODE에서 자동 반영할 최소 severity', options: ['critical', 'major', 'minor'] },
  'agile.adversarial_review.clarification_blocking_severities': '사용자 확인이 필요한 적대적 검토 severity 목록',
  'agile.adversarial_review.clarification_batch_max_items': '한 번에 묶어 확인할 적대적 검토 항목 최대 개수',
  'agile.adversarial_review.parallel_in_auto_mode': 'AUTO_MODE에서 활성화된 관점을 병렬 실행할지 여부',
  'server.port': '대시보드 포트',
  'server.host': '대시보드 호스트',
  'concurrency.max_parallel_tasks': '최대 병렬 태스크 수',
  'concurrency.max_parallel_reviews': '최대 병렬 리뷰 수',
  'concurrency.batch_max_parallel_reqs': '배치 승인 시 최대 병렬 REQ 수',
  'concurrency.queue_strategy': { description: '큐 전략', options: ['fifo', 'priority'] },
  'timeouts.cli_default_ms': 'CLI 기본 타임아웃 (5분)',
  'timeouts.cli_large_task_ms': '대규모 태스크 타임아웃 (30분)',
  'timeouts.pre_check_ms': '사전 검증 타임아웃 (2분)',
  'timeouts.merge_ms': 'Merge 타임아웃 (1분)',
  'timeouts.user_approval_ms': '사용자 승인 대기 타임아웃',
  'timeouts.dashboard_health_check_ms': '대시보드 헬스체크 (10초)',
  'worktree.root_directory': 'worktree 루트 경로',
  'worktree.max_active': '최대 활성 worktree 수',
  'worktree.base_branch': 'worktree 기준 브랜치',
  'worktree.protected_branches': '보호할 브랜치 태그 목록 (배열)',
  'worktree.stale_timeout_hours': 'stale 판정 시간',
  'worktree.auto_cleanup_on_cancel': '취소 시 자동 정리',
  'retry.max_cli_retries': 'CLI 최대 재시도 횟수',
  'retry.max_fallback_depth': '최대 fallback 깊이',
  'retry.backoff_base_ms': '재시도 백오프 기준 (ms)',
  'delegation.host': { description: '위임 명령 선택 기준 host', options: ['auto', 'codex', 'claude', 'headless'] },
  'delegation.default_provider': { description: '기본 위임 provider', options: ['codex', 'agy', 'claude'] },
  'delegation.provider_priority': '위임 provider 우선순위',
  'delegation.transport_policy': {
    description: '위임 transport 정책. same-host-native-first는 같은 host/provider의 native agent를 우선하고, external-only는 기존 CLI/wrapper만 사용합니다. 기존 native_codex_subagents.enabled=false는 external-only로 migration됩니다.',
    options: ['same-host-native-first', 'external-only'],
  },
  'delegation.native.enabled': '같은 host/provider의 native 위임 허용 여부. opt-out 시 delegation.transport_policy도 external-only로 함께 설정합니다.',
  'delegation.native.scope': {
    description: 'Native 위임을 허용할 작업 범위. 기존 native_codex_subagents.scope alias는 이 canonical 값으로 migration됩니다.',
    options: ['all', 'review-and-exploration-only', 'review-only', 'exploration-only', 'implementation-only', 'none'],
  },
  'delegation.orca.enabled': '로컬 Orca 터미널에서 보호된 provider CLI runner를 실행합니다. MST worktree와 lifecycle은 그대로 유지되며 기본값은 꺼짐입니다.',
  'delegation.native_codex_subagents.enabled': 'Legacy read/migration alias입니다. 새 설정은 delegation.transport_policy와 delegation.native.enabled를 사용하며 canonical 값이 충돌 시 우선합니다.',
  'delegation.native_codex_subagents.scope': 'Legacy read/migration alias입니다. 새 설정은 delegation.native.scope를 사용하며 canonical 값이 충돌 시 우선합니다.',
  'delegation.codex_sandbox': 'Codex CLI sandbox 기본 정책',
  'delegation.monitor_interval_ms': '위임 실행 모니터링 간격',
  'delegation.monitor_tail_lines': '모니터링 시 읽을 로그 tail 라인 수',
  'delegation.monitor_anomaly_patterns': '위임 실행 이상 신호 패턴',
  'history.retention_days': '이력 보존 기간 (일)',
  'history.auto_archive': '자동 아카이브',
  'archive.max_active_sessions': '최대 활성 세션 수',
  'archive.archive_retention_days': '아카이브 보존 기간 (null=무기한)',
  'archive.auto_archive_on_create': '세션 생성 시 초과분 자동 아카이브',
  'archive.auto_archive_on_complete': '완료 시 자동 아카이브',
  'archive.archive_directory': '아카이브 저장 경로',
  'notifications.terminal': '터미널 알림',
  'notifications.dashboard': '대시보드 알림',
  'realtime.protocol': { description: '실시간 프로토콜 (SSE)', options: ['sse'] },
  'realtime.debounce_ms': '이벤트 디바운스 (ms)',
  'debug.enabled': '디버그 모드',
  'debug.log_level': { description: '로그 레벨', options: ['info', 'debug', 'trace'] },
  'debug.log_prompts': '프롬프트 로깅',
  'discussion.response_char_limit': 'Discussion 응답 글자 제한',
  'discussion.critique_char_limit': 'Discussion Critic 글자 제한',
  'discussion.default_max_rounds': '기본 최대 라운드 수',
  'discussion.max_rounds_upper_limit': '최대 라운드 상한',
  'discussion.agents.codex': 'Discussion Codex 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'discussion.agents.codex.count': 'Discussion Codex 참여자 수 (0=제외)',
  'discussion.agents.codex.tier': { description: 'Discussion Codex tier (premium/economy)', options: ['premium', 'economy'] },
  'discussion.agents.agy': 'Discussion AGY 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'discussion.agents.agy.count': 'Discussion AGY 참여자 수 (0=제외)',
  'discussion.agents.agy.tier': { description: 'Discussion AGY tier (premium/economy)', options: ['premium', 'economy'] },
  'discussion.agents.claude': 'Discussion Claude 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'discussion.agents.claude.count': 'Discussion Claude 참여자 수 (0=제외)',
  'discussion.agents.claude.tier': { description: 'Discussion Claude tier (premium/economy)', options: ['premium', 'economy'] },
  'ideation.opinion_char_limit': 'Ideation 의견 글자 제한',
  'ideation.critique_char_limit': 'Ideation Critic 글자 제한',
  'ideation.agents.codex': 'Ideation Codex 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'ideation.agents.codex.count': 'Ideation Codex 참여자 수 (0=제외)',
  'ideation.agents.codex.tier': { description: 'Ideation Codex tier (premium/economy)', options: ['premium', 'economy'] },
  'ideation.agents.agy': 'Ideation AGY 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'ideation.agents.agy.count': 'Ideation AGY 참여자 수 (0=제외)',
  'ideation.agents.agy.tier': { description: 'Ideation AGY tier (premium/economy)', options: ['premium', 'economy'] },
  'ideation.agents.claude': 'Ideation Claude 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'ideation.agents.claude.count': 'Ideation Claude 참여자 수 (0=제외)',
  'ideation.agents.claude.tier': { description: 'Ideation Claude tier (premium/economy)', options: ['premium', 'economy'] },
  'prereview.agents.codex': 'Pre-review Codex 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'prereview.agents.codex.count': 'Pre-review Codex 에이전트 수 (0=제외)',
  'prereview.agents.codex.tier': { description: 'Pre-review Codex tier (premium/economy)', options: ['premium', 'economy'] },
  'prereview.agents.agy': 'Pre-review AGY 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'prereview.agents.agy.count': 'Pre-review AGY 에이전트 수 (0=제외)',
  'prereview.agents.agy.tier': { description: 'Pre-review AGY tier (premium/economy)', options: ['premium', 'economy'] },
  'prereview.agents.claude': 'Pre-review Claude 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'prereview.agents.claude.count': 'Pre-review Claude 에이전트 수 (0=제외)',
  'prereview.agents.claude.tier': { description: 'Pre-review Claude tier (premium/economy)', options: ['premium', 'economy'] },
  'collaborative_debug.finding_char_limit': '조사 결과 글자 제한',
  'collaborative_debug.merge_wait_ms': '에이전트 합류 대기 시간 (60초)',
  'collaborative_debug.auto_trigger_from_request': '/mst:request에서 디버그 의도 시 자동 트리거',
  'debug.agents.codex': 'Debug Codex 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'debug.agents.codex.count': 'Debug 조사 Codex 에이전트 수 (0=제외)',
  'debug.agents.codex.tier': { description: 'Debug Codex tier (premium/economy)', options: ['premium', 'economy'] },
  'debug.agents.agy': 'Debug AGY 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'debug.agents.agy.count': 'Debug 조사 AGY 에이전트 수 (0=제외)',
  'debug.agents.agy.tier': { description: 'Debug AGY tier (premium/economy)', options: ['premium', 'economy'] },
  'debug.agents.claude': 'Debug Claude 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'debug.agents.claude.count': 'Debug 조사 Claude 에이전트 수 (0=제외)',
  'debug.agents.claude.tier': { description: 'Debug Claude tier (premium/economy)', options: ['premium', 'economy'] },
  'explore.agents.codex': 'Explore Codex 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'explore.agents.codex.count': 'Explore Codex 탐색 에이전트 수 (0=제외)',
  'explore.agents.codex.tier': { description: 'Explore Codex tier (premium/economy)', options: ['premium', 'economy'] },
  'explore.agents.agy': 'Explore AGY 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'explore.agents.agy.count': 'Explore AGY 탐색 에이전트 수 (0=제외)',
  'explore.agents.agy.tier': { description: 'Explore AGY tier (premium/economy)', options: ['premium', 'economy'] },
  'explore.agents.claude': 'Explore Claude 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'explore.agents.claude.count': 'Explore Claude 탐색 에이전트 수 (0=제외)',
  'explore.agents.claude.tier': { description: 'Explore Claude tier (premium/economy)', options: ['premium', 'economy'] },
  'd3.agents.codex': 'D3 Codex 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'd3.agents.codex.count': 'D3 Codex 에이전트 수 (0=제외)',
  'd3.agents.codex.tier': { description: 'D3 Codex tier (premium/economy)', options: ['premium', 'economy'] },
  'd3.agents.agy': 'D3 AGY 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'd3.agents.agy.count': 'D3 AGY 에이전트 수 (0=제외)',
  'd3.agents.agy.tier': { description: 'D3 AGY tier (premium/economy)', options: ['premium', 'economy'] },
  'd3.agents.claude': 'D3 Claude 에이전트 설정 ({ count, tier } 또는 숫자 count 하위호환)',
  'd3.agents.claude.count': 'D3 Claude 에이전트 수 (0=제외)',
  'd3.agents.claude.tier': { description: 'D3 Claude tier (premium/economy)', options: ['premium', 'economy'] },
  'models.providers.codex.premium': 'Codex premium 모델 ID',
  'models.providers.codex.economy': 'Codex economy 모델 ID',
  'models.providers.codex.default_tier': { description: 'Codex 기본 tier (premium/economy)', options: ['premium', 'economy'] },
  'models.providers.agy.premium': 'AGY premium 모델 ID',
  'models.providers.agy.economy': 'AGY economy 모델 ID',
  'models.providers.agy.default_tier': { description: 'AGY 기본 tier (premium/economy)', options: ['premium', 'economy'] },
  'models.providers.claude.premium': 'Claude premium 모델 ID',
  'models.providers.claude.economy': 'Claude economy 모델 ID',
  'models.providers.claude.default_tier': { description: 'Claude 기본 tier (premium/economy)', options: ['premium', 'economy'] },
  'models.roles.pm_conductor.provider': { description: 'PM 지휘자 provider', options: ['codex', 'agy', 'claude'] },
  'models.roles.pm_conductor.tier': { description: 'PM 지휘자 tier', options: ['premium', 'economy'] },
  'models.roles.architect.provider': { description: '아키텍트 provider', options: ['codex', 'agy', 'claude'] },
  'models.roles.architect.tier': { description: '아키텍트 tier', options: ['premium', 'economy'] },
  'models.roles.developer': '개발자 풀 (primary/fallback 순서)',
  'models.roles.developer.0': '주 개발자 (primary)',
  'models.roles.developer.0.provider': { description: '주 개발자 provider', options: ['codex', 'agy', 'claude'] },
  'models.roles.developer.0.tier': { description: '주 개발자 tier', options: ['premium', 'economy'] },
  'models.roles.developer.1': '보조 개발자 (fallback)',
  'models.roles.developer.1.provider': { description: '보조 개발자 provider', options: ['codex', 'agy', 'claude'] },
  'models.roles.developer.1.tier': { description: '보조 개발자 tier', options: ['premium', 'economy'] },
  'models.roles.developer_claude.provider': 'Claude 개발자 provider',
  'models.roles.developer_claude.tier': { description: 'Claude 개발자 tier', options: ['premium', 'economy'] },
  'models.roles.developer_claude.enabled': 'Claude 개발자 legacy/fallback 활성화 여부',
  'models.roles.reviewer': '리뷰어 풀 (primary/fallback 순서)',
  'models.roles.reviewer.0': '주 리뷰어 (primary)',
  'models.roles.reviewer.0.provider': { description: '주 리뷰어 provider', options: ['codex', 'agy', 'claude'] },
  'models.roles.reviewer.0.tier': { description: '주 리뷰어 tier', options: ['premium', 'economy'] },
  'models.roles.reviewer.1': '보조 리뷰어 (fallback)',
  'models.roles.reviewer.1.provider': { description: '보조 리뷰어 provider', options: ['codex', 'agy', 'claude'] },
  'models.roles.reviewer.1.tier': { description: '보조 리뷰어 tier', options: ['premium', 'economy'] },
  'code_review.enabled': '코드 리뷰 활성화',
  'code_review.agents': '코드 리뷰 참여 에이전트 수',
  'code_review.agent_roster': '코드 리뷰 에이전트 명단',
  'code_review.parallel': '병렬 코드 리뷰',
  'code_review.use_native_review': 'Codex 네이티브 review 서브커맨드 사용 여부',
  'code_review.native_review_prompt': 'Codex 네이티브 review에 추가로 전달할 프롬프트',
  'cleanup.ideation_keep_count': 'Ideation 세션 유지 수',
  'cleanup.discussion_keep_count': 'Discussion 세션 유지 수',
  'cleanup.debug_keep_count': 'Debug 세션 유지 수',
  'cleanup.old_request_threshold_hours': '오래된 요청 판단 기준 (시간)',
  'stitch.enabled': 'Stitch UI 설계 기능 활성화',
  'stitch.auto_detect': 'UI 변경 자동 감지',
  'stitch.auto_trigger': '자동 Stitch 실행',
  'stitch.project_id': 'Stitch 프로젝트 ID',
  'stitch.failure_policy': { description: 'Stitch 실패 정책', options: ['skip', 'strict'] },
  'workflow.auto_approve_on_unblock': 'Unblock 시 자동 승인 여부',
  'workflow.spec_prereview_max_iterations': 'Pre-review 최대 반복 횟수',
  'workflow.spec_prereview_escalation_trigger': { description: 'Pre-review 에스컬레이션 트리거 기준', options: ['critical', 'major', 'minor'] },
  'workflow.spec_prereview_minor_escalation_threshold': 'Pre-review MINOR 에스컬레이션 임계값',
  'review.auto_review': '자동 리뷰 활성화',
  'review.max_iterations': '리뷰 최대 반복 횟수',
  'review.cross_validation.enabled': '교차 검증 활성화',
  'review.cross_validation.line_proximity': '교차 검증 라인 근접 기준',
  'review.roles.code_reviewer.agent': '코드 리뷰어 에이전트',
  'review.roles.code_reviewer.tier': { description: '코드 리뷰어 tier (premium/economy)', options: ['premium', 'economy'] },
  'review.roles.arch_reviewer.agent': '아키텍처 리뷰어 에이전트',
  'review.roles.arch_reviewer.tier': { description: '아키텍처 리뷰어 tier (premium/economy)', options: ['premium', 'economy'] },
  'review.roles.ui_reviewer.agent': 'UI 리뷰어 에이전트',
  'review.roles.ui_reviewer.tier': { description: 'UI 리뷰어 tier (premium/economy)', options: ['premium', 'economy'] },
  'review.roles.browser_tester.agent': { description: '브라우저 테스터 에이전트 (browser-test AC 위임 대상)', options: ['codex', 'agy', 'claude'] },
  'review.roles.browser_tester.tier': { description: '브라우저 테스터 tier (premium/economy)', options: ['premium', 'economy'] },
  'review.roles.intent_fidelity.agent': { description: '의도 충실도 리뷰어 에이전트', options: ['codex', 'agy', 'claude'] },
  'review.roles.intent_fidelity.tier': { description: '의도 충실도 리뷰어 tier', options: ['premium', 'economy'] },
  'review.roles.impact_reviewer.enabled': '영향도 리뷰어 활성화',
  'review.roles.impact_reviewer.agent': { description: '영향도 리뷰어 에이전트', options: ['codex', 'agy', 'claude'] },
  'review.roles.impact_reviewer.tier': { description: '영향도 리뷰어 tier (premium/economy)', options: ['premium', 'economy'] },
  'review.roles.impact_reviewer.enhanced_analysis': '영향도 리뷰어 확장 분석 활성화',
  'review.roles.adversarial_reviewer.enabled': 'Adversarial 리뷰어 활성화',
  'review.roles.adversarial_reviewer.agent': { description: 'Adversarial 리뷰어 에이전트', options: ['codex', 'agy', 'claude'] },
  'review.roles.adversarial_reviewer.tier': { description: 'Adversarial 리뷰어 tier (premium/economy)', options: ['premium', 'economy'] },
  'review.roles.adversarial_reviewer.trigger': { description: 'Adversarial 리뷰 트리거 모드', options: ['auto', 'always', 'manual'] },
  'review.roles.adversarial_reviewer.attack_surfaces': '검토할 공격 표면 목록',
  'review.roles.adversarial_reviewer.max_findings': '최대 Finding 개수',
  'review.roles.adversarial_reviewer.confidence_threshold': 'Finding 신뢰도 임계값 (0~1)',
  'review.severity_auto_fix.enabled': '심각도 기반 자동 수정 활성화',
  'review.severity_auto_fix.pm_direct_fix_enabled': 'PM 직접 수정 활성화',
  'review.severity_auto_fix.pm_direct_fix_max_files': 'PM 직접 수정 최대 파일 수',
  'review.severity_auto_fix.pm_direct_fix_max_diff_lines': 'PM 직접 수정 최대 diff 라인 수',
  'review.severity_auto_fix.minor_skip_threshold': 'MINOR 이슈 스킵 임계값',
  'review.severity_auto_fix.security_override_keywords': '보안 오버라이드 키워드 목록',
  'plan_review.enabled': 'Plan Review 활성화',
  'plan_review.parallel': 'Plan Review 병렬 실행',
  'plan_review.max_iterations': 'Plan Review 최대 반복 횟수',
  'plan_review.escalation_trigger': { description: 'Plan Review 에스컬레이션 트리거', options: ['critical', 'major', 'minor'] },
  'plan_review.minor_escalation_threshold': 'Plan Review MINOR 에스컬레이션 임계값',
  'plan_review.roles.architect.enabled': '아키텍트 리뷰어 활성화',
  'plan_review.roles.architect.agent': '아키텍트 리뷰어 에이전트',
  'plan_review.roles.architect.tier': { description: '아키텍트 리뷰어 tier (premium/economy)', options: ['premium', 'economy'] },
  'plan_review.roles.devils_advocate.enabled': '악마의 대변인 리뷰어 활성화',
  'plan_review.roles.devils_advocate.agent': '악마의 대변인 리뷰어 에이전트',
  'plan_review.roles.devils_advocate.tier': { description: '악마의 대변인 리뷰어 tier (premium/economy)', options: ['premium', 'economy'] },
  'plan_review.roles.completeness.enabled': '완전성 검토 리뷰어 활성화',
  'plan_review.roles.completeness.agent': '완전성 검토 리뷰어 에이전트',
  'plan_review.roles.completeness.tier': { description: '완전성 검토 리뷰어 tier (premium/economy)', options: ['premium', 'economy'] },
  'plan_review.roles.ux_reviewer.enabled': 'UX 리뷰어 활성화',
  'plan_review.roles.ux_reviewer.agent': 'UX 리뷰어 에이전트',
  'plan_review.roles.ux_reviewer.tier': { description: 'UX 리뷰어 tier (premium/economy)', options: ['premium', 'economy'] },
  'phase1_exploration.roles.symbol_tracing.agent': 'Phase 1 정밀 심볼 추적 에이전트',
  'phase1_exploration.roles.symbol_tracing.enabled': 'Phase 1 심볼 추적 역할 활성화 여부',
  'phase1_exploration.roles.symbol_tracing.tier': { description: 'Phase 1 심볼 추적 tier (premium/economy)', options: ['premium', 'economy'] },
  'phase1_exploration.roles.broad_scan.agent': 'Phase 1 광역 탐색 에이전트',
  'phase1_exploration.roles.broad_scan.enabled': 'Phase 1 광역 탐색 역할 활성화 여부',
  'phase1_exploration.roles.broad_scan.tier': { description: 'Phase 1 광역 탐색 tier (premium/economy)', options: ['premium', 'economy'] },
  'intent_fidelity': '의도 충실도 검증 설정',
  'intent_fidelity.enabled': '의도 충실도 검증 활성화 여부',
  'intent_fidelity.mode': '의도 충실도 검증 모드',
  'intent_fidelity.exclude_dirs': '의도 충실도 검증 제외 디렉터리 목록',
  'fact_check.agent.provider': { description: '팩트체크 provider', options: ['codex', 'agy', 'claude'] },
  'fact_check.agent.tier': { description: '팩트체크 tier', options: ['premium', 'economy'] },
  'auto_mode': '자동 실행 모드 설정',
  'auto_mode.plan': '계획 단계 자동 실행 여부',
  'auto_mode.request': '요청 단계 자동 실행 여부',
  'auto_mode.review': '리뷰 단계 자동 실행 여부',
  'auto_mode.confidence_threshold': '자동 실행 신뢰도 임계값',
  'auto_mode.max_review_iterations': '자동 리뷰 최대 반복 횟수',
  'cleanup.plans_keep_count': 'Plan 세션 유지 수',
  'plan_qa_presets.test_strategy': {
    description: '테스트 전략 프리셋 (ask=매번 질문)',
    options: ['ask', 'apply-80', 'apply-90', 'apply-no-coverage', 'skip'],
  },
  'plan_qa_presets.loop_exit': {
    description: 'Loop 종료 조건 프리셋 (ask=매번 질문)',
    options: ['ask', 'default_pass', 'convergence', 'fixed_n'],
  },
  'plan_qa_presets.loop_exit_n': '고정 반복 횟수 (loop_exit=fixed_n 시 사용)',
  'test_enforcement.enabled': '소스 코드 수정 시 테스트 작성/실행 강제 여부 (true=강제, false=권장)',
  'test_enforcement.backend_tdd': '백엔드 태스크에 TDD 순서 (테스트 먼저 → 구현) 강제',
  'test_enforcement.web_execution_test': '웹/프론트엔드 태스크에 실행 테스트 (playwright/browser) 강제',
  'test_enforcement.exempt_patterns': '테스트 면제 파일 패턴 (이 패턴에 100% 매칭되면 테스트 면제)',
  'test_enforcement.require_exemption_reason': '테스트 면제 시 사유 기록 필수 여부',
};

export const getDescription = (
  description: string | SettingMeta | undefined
): string | undefined => {
  if (typeof description === 'string') {
    return description;
  }

  return description?.description;
};

export const getOptions = (
  description: string | SettingMeta | undefined
): string[] | undefined => {
  if (!description || typeof description === 'string') {
    return undefined;
  }

  return description.options;
};
