# Generated by scripts/build_state_schema.py. DO NOT EDIT.
from __future__ import annotations

TASK_STATUSES = ('pending', 'queued', 'executing', 'pre_check', 'pre_check_failed', 'review', 'feedback', 'merging', 'merge_conflict', 'done', 'failed', 'cancelled')
TERMINAL = frozenset(('done', 'failed', 'cancelled'))
TRANSITIONS = [
  {
    "from": "pending",
    "to": "queued",
    "condition": "PM decides execution order",
    "guard": "no pending predecessors or predecessors completed"
  },
  {
    "from": "queued",
    "to": "executing",
    "condition": "Parallel slot available",
    "guard": "active_tasks < max_parallel_tasks"
  },
  {
    "from": "executing",
    "to": "pre_check",
    "condition": "CLI exit code === 0",
    "guard": "commit exists in worktree"
  },
  {
    "from": "executing",
    "to": "failed",
    "condition": "CLI exit code !== 0 and retries exhausted",
    "guard": "retry_count >= max_retries"
  },
  {
    "from": "pre_check",
    "to": "review",
    "condition": "Typecheck + tests pass"
  },
  {
    "from": "pre_check",
    "to": "pre_check_failed",
    "condition": "Typecheck or tests fail"
  },
  {
    "from": "pre_check_failed",
    "to": "executing",
    "condition": "Auto retry with feedback attached",
    "guard": "retry_count < max_retries"
  },
  {
    "from": "pre_check_failed",
    "to": "feedback",
    "condition": "Retries exhausted",
    "guard": "retry_count >= max_retries"
  },
  {
    "from": "review",
    "to": "feedback",
    "condition": "FAIL or PARTIAL verdict"
  },
  {
    "from": "review",
    "to": "merging",
    "condition": "PASS verdict -- all acceptance criteria met, proceed to merge"
  },
  {
    "from": "feedback",
    "to": "executing",
    "condition": "Root cause classified as implementation error"
  },
  {
    "from": "feedback",
    "to": "pending",
    "condition": "Root cause classified as insufficient spec"
  },
  {
    "from": "merging",
    "to": "done",
    "condition": "Merge succeeded"
  },
  {
    "from": "merging",
    "to": "merge_conflict",
    "condition": "Merge conflict detected"
  },
  {
    "from": "*",
    "to": "cancelled",
    "condition": "/mc invoked",
    "guard": "CLI process receives SIGTERM"
  },
  {
    "from": "*",
    "to": "failed",
    "condition": "Unrecoverable system error"
  }
]
RECOVERY_ACTIONS = ('retry', 'rollback', 'manual', 'abort')
ACTIVE_PHASE_STATUSES = frozenset(('pending', 'phase1_analysis', 'phase1_spec_drafting', 'phase2_pending', 'phase2_approving', 'phase2_execution', 'executing', 'reviewing', 'phase3_review', 'merging', 'merge_conflict', 'merge_conflict_user_resolving'))
